### ISSUE TITLE
Ankh panics on some inputs

### ISSUE THREAD

**Issue by dbemiller** [appnexus/ankh#97]
## Steps to reproduce

Make a `minimal-chart` directory with the following `Chart.yaml`:

```
name: my-app
version: 1.0.0
```

And the following `minimal-chart/templates/config-map.yaml`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "my-app-{{ .Release.Name }}"
  labels:
	app: "my-app"
    release: {{ .Release.Name }}
data:
  SOME_CONFIG: "any-value"
```

Then run `ankh lint chart-path=./minimal-chart`, choose some environment, and leave the namespace blank.

## Observed

Ankh panics with:

```
panic: attempted to parse unknown event: none [recovered]
	panic: attempted to parse unknown event: none [recovered]
	panic: attempted to parse unknown event: none

goroutine 1 [running]:
github.com/jawher/mow%2ecli.(*step).run(0xc000368600, 0x14e13a0, 0xc0002280f0)
	/Users/dbemiller/go/pkg/mod/github.com/jawher/mow.cli@v1.0.3/flow.go:28 +0xd6
github.com/jawher/mow%2ecli.(*step).run(0xc000368660, 0x14e13a0, 0xc0002280f0)
	/Users/dbemiller/go/pkg/mod/github.com/jawher/mow.cli@v1.0.3/flow.go:20 +0xbe
github.com/jawher/mow%2ecli.(*step).run(0xc0003691d0, 0x14e13a0, 0xc0002280f0)
	/Users/dbemiller/go/pkg/mod/github.com/jawher/mow.cli@v1.0.3/flow.go:20 +0xbe
github.com/jawher/mow%2ecli.(*step).callDo.func1(0xc000369200, 0x0, 0x0)
	/Users/dbemiller/go/pkg/mod/github.com/jawher/mow.cli@v1.0.3/flow.go:41 +0x4a
panic(0x14e13a0, 0xc0002280f0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
gopkg.in/yaml%2ev2.handleErr(0xc00073c798)
	/Users/dbemiller/go/pkg/mod/gopkg.in/yaml.v2@v2.2.1/yaml.go:249 +0x9a
panic(0x14e13a0, 0xc0002280f0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
gopkg.in/yaml%2ev2.(*parser).parse(0xc000356000, 0xc00007e100)
	/Users/dbemiller/go/pkg/mod/gopkg.in/yaml.v2@v2.2.1/decode.go:158 +0x251
gopkg.in/yaml%2ev2.(*Decoder).Decode(0xc00073c848, 0x14c7bc0, 0xc0001081e0, 0x0, 0x0)
	/Users/dbemiller/go/pkg/mod/gopkg.in/yaml.v2@v2.2.1/yaml.go:122 +0xdf
github.com/appnexus/ankh/helm.helmLint(0xc000362480, 0xc0000fe000, 0xbb, 0x0, 0x0, 0xc000600400)
	/Users/dbemiller/code/ankh/helm/lintstage.go:106 +0x232
...
```

## Expected

An error message that describes what's broken or missing.

**Comment by esmet** [comment]
FWIW this part of the yaml contains spaces, and the parser does not like that:

```
metadata:
  name: "my-app-{{ .Release.Name }}"
  labels:
	app: "my-app"
    release: {{ .Release.Name }}
```
